2021-01-12 22:55:42,639 INFO    MainThread:3935 [wandb_setup.py:_flush():70] setting env: {}
2021-01-12 22:55:42,639 INFO    MainThread:3935 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-12 22:55:42,639 INFO    MainThread:3935 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-12 22:55:42,639 INFO    MainThread:3935 [wandb_init.py:_log_setup():303] Logging user logs to /Users/stephanehatgiskessell/Desktop/RL_research_algs/PPO/wandb/run-20210112_225542-6pane44t/logs/debug.log
2021-01-12 22:55:42,639 INFO    MainThread:3935 [wandb_init.py:_log_setup():304] Logging internal logs to /Users/stephanehatgiskessell/Desktop/RL_research_algs/PPO/wandb/run-20210112_225542-6pane44t/logs/debug-internal.log
2021-01-12 22:55:43,605 INFO    MainThread:3935 [wandb_run.py:_console_start():1237] atexit reg
2021-01-12 22:55:43,605 INFO    MainThread:3935 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2021-01-12 22:55:43,606 INFO    MainThread:3935 [wandb_run.py:_redirect():1107] Redirecting console.
2021-01-12 22:55:43,606 INFO    MainThread:3935 [redirect.py:install():204] install start
2021-01-12 22:55:43,607 INFO    MainThread:3935 [redirect.py:install():219] install stop
2021-01-12 22:55:43,607 INFO    MainThread:3935 [redirect.py:install():204] install start
2021-01-12 22:55:43,607 INFO    MainThread:3935 [redirect.py:install():219] install stop
2021-01-12 22:55:43,607 INFO    MainThread:3935 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-12 22:55:43,620 INFO    MainThread:3935 [wandb_config.py:__setitem__():135] config set learning_rate = 0.0001 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fb5ad92e470>>
2021-01-12 22:55:43,620 INFO    MainThread:3935 [wandb_run.py:_config_callback():549] config_cb learning_rate 0.0001 {'_wandb': {'cli_version': '0.10.12', 'python_version': '3.6.12', 'is_jupyter_run': False, 'is_kaggle_kernel': False, 'framework': 'torch'}, 'learning_rate': 0.0001}
2021-01-12 22:55:43,622 INFO    MainThread:3935 [wandb_watch.py:watch():35] Watching
2021-01-12 22:55:44,298 INFO    MainThread:3935 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2021-01-12 22:55:44,299 INFO    MainThread:3935 [wandb_run.py:_restore():1179] restore
2021-01-12 22:55:44,299 INFO    MainThread:3935 [redirect.py:uninstall():223] uninstall start
2021-01-12 22:55:44,299 INFO    MainThread:3935 [redirect.py:_stop():278] _stop: stdout
2021-01-12 22:55:44,300 INFO    MainThread:3935 [redirect.py:_stop():284] _stop closed: stdout
2021-01-12 22:55:44,300 INFO    stdout    :3935 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2021-01-12 22:55:44,300 INFO    stdout    :3935 [redirect.py:_pipe_relay():136] relay done done: stdout
2021-01-12 22:55:44,300 INFO    MainThread:3935 [redirect.py:_stop():290] _stop joined: stdout
2021-01-12 22:55:44,300 INFO    MainThread:3935 [redirect.py:_stop():292] _stop rd closed: stdout
2021-01-12 22:55:44,300 INFO    MainThread:3935 [redirect.py:uninstall():227] uninstall done
2021-01-12 22:55:44,300 INFO    MainThread:3935 [redirect.py:uninstall():223] uninstall start
2021-01-12 22:55:44,301 INFO    MainThread:3935 [redirect.py:_stop():278] _stop: stderr
2021-01-12 22:55:44,301 INFO    MainThread:3935 [redirect.py:_stop():284] _stop closed: stderr
2021-01-12 22:55:44,301 INFO    stderr    :3935 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2021-01-12 22:55:44,301 INFO    stderr    :3935 [redirect.py:_pipe_relay():136] relay done done: stderr
2021-01-12 22:55:44,301 INFO    MainThread:3935 [redirect.py:_stop():290] _stop joined: stderr
2021-01-12 22:55:44,301 INFO    MainThread:3935 [redirect.py:_stop():292] _stop rd closed: stderr
2021-01-12 22:55:44,301 INFO    MainThread:3935 [redirect.py:uninstall():227] uninstall done
2021-01-12 22:55:44,303 INFO    MainThread:3935 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "9aeb3b9d8ab64f66811e98fa3f65ecd1"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 500
      total_bytes: 500
    }
  }
}

2021-01-12 22:55:46,307 INFO    MainThread:3935 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "9b5b9eb06f6c4a4787e3c9c570766050"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 3959
      total_bytes: 3959
    }
  }
}

2021-01-12 22:55:47,425 INFO    MainThread:3935 [wandb_run.py:_show_files():1536] logging synced files
2021-01-12 22:55:47,427 INFO    MainThread:3935 [internal.py:handle_exit():138] Internal process exited
